### ISSUE TITLE
Dropdown menu is no dropdown anymore

### ISSUE THREAD

**Issue by jmuheim** [burtlo/yard-cucumber#37]
Since I have installed `yard-cucumber` (and it really is nice, thank you!), the dropdown menu on the upper right (with Features, Tags, Steps, etc.) doesn't drop down anymore but it loads a new page with the dropdown content. Any idea why this happens? Thanks.

**Comment by snowe2010** [comment]
I am also seeing this problem. It's very bothersome. I thought it might have something to do with another javascript error I'm getting in the console

```
ReferenceError: hasFrames is not defined
```

**Comment by snowe2010** [comment]
It looks like it's a problem with serving with `yard server` vs opening the files manually
