### ISSUE TITLE
Invalid configuration file

### ISSUE THREAD

**Issue by luvs** [burtlo/yard-cucumber#47]
After install yard-cucumber YARD stared write error:

yardoc 'features/attach_file/cms_delete_attach_file/cms_delete_attach_file.feature'
[error]: Invalid configuration file, using default options.
[warn]: Syntax error in `features/attach_file/cms_delete_attach_file/cms_delete_attach_file.feature`:(2,8): syntax error, unexpected ':', expecting end-of-input
[warn]: ParserSyntaxError: syntax error in `features/attach_file/cms_delete_attach_file/cms_delete_attach_file.feature`:(2,8): syntax error, unexpected ':', expecting end-of-input
[warn]: Stack trace:
        /home/luvs/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/yard-0.8.6.1/lib/yard/parser/ruby/ruby_parser.rb:542:in `on_parse_error'
        /home/luvs/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/yard-0.8.6.1/lib/yard/parser/ruby/ruby_parser.rb:50:in`parse'
        /home/luvs/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/yard-0.8.6.1/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
        /home/luvs/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/yard-0.8.6.1/lib/yard/parser/ruby/ruby_parser.rb:15:in`parse'
        /home/luvs/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/yard-0.8.6.1/lib/yard/parser/source_parser.rb:439:in `parse'
        /home/luvs/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/gems/yard-0.8.6.1/lib/yard/parser/source_parser.rb:44:in`block in parse'

Files:           0
Modules:         0 (    0 undocumented)
Classes:         0 (    0 undocumented)
Constants:       0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 0.00% documented

Gem list:
bundler (1.3.5)
cucumber (1.3.2)
diff-lcs (1.2.4)
gherkin (2.12.0)
io-console (0.4.2)
json (1.8.0, 1.7.7)
log4r (1.1.10)
minitest (5.0.3, 4.3.2)
multi_json (1.7.4)
nokogiri (1.5.9)
parallel (0.6.5)
parallel_tests (0.13.3)
plugin_manager (1.5)
psych (2.0.0)
rake (10.0.4, 0.9.6)
rdoc (4.0.1, 4.0.0)
rspec (2.13.0)
rspec-core (2.13.1)
rspec-expectations (2.13.0)
rspec-mocks (2.13.1)
ruby-oci8 (2.1.5)
ruby-plsql (0.5.0)
rubygems-update (2.0.3)
test-unit (2.5.5, 2.0.0.0)
thor (0.18.1)
yard (0.8.6.1)
yard-cucumber (2.2.3)
zip (2.0.2)

**Comment by vikramvi** [comment]
@luvs  @jonathanchrisp  Even I'm facing same problem can you please share your Gemfile and Gemfile.lock
