### ISSUE TITLE
Step Definitions are getting missed when parsing the step definitions because of new standard

### ISSUE THREAD

**Issue by burtlo** [burtlo/yard-cucumber#48]
> Also, since cucumber/gherkin is now recommending parentheses around step definition regexes https://github.com/cucumber/cucumber/issues/328 , that means IDEs like RubyMine are including them with default step-def generation. They then get missed during step:>step-def matching when I switch to the older cucumber/gherkin gems to generate docs. I'm correcting for that with my script but it's a bit of a kludge. Since your gem utilizes the loaded cucumber/gherkin to generate its parsing rules, I imagine the need for that handling would go away with a yard-cucumber update.

**Comment by snowe2010** [comment]
We're encountering this issue. What is the fix?
