### ISSUE TITLE
"uninitialized constant YARD" when yard gem not in Gemfile

### ISSUE THREAD

**Issue by haxney** [burtlo/yard-cucumber#56]
I had a `Gemfile` with `gem 'yard-cucumber'` in it, which pulls in the `yard` dependency, but when I ran `rake yard`, I would get the error:

```
rake aborted!
uninitialized constant YARD
/home/haxney/.rvm/gems/ruby-2.0.0-p247@railskating/gems/yard-cucumber-2.3.2/lib/yard/code_objects/cucumber/base.rb:1:in `<top (required)>'
/home/haxney/.rvm/gems/ruby-2.0.0-p247@railskating/gems/yard-cucumber-2.3.2/lib/yard-cucumber.rb:8:in `<top (required)>'
/home/haxney/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
```

I found that either adding a `require 'yard'` to the top of `yard-cucumber-2.3.2/lib/yard/code_objects/cucumber/base.rb:1` or adding `gem 'yard'` to my `Gemfile` solved the problem, but `yard-cucumber` should be able to function even without the user having to list `gem 'yard'` in their `Gemfile`.

**Comment by nrser** [comment]
Sharing some info as I look into this...

The offending `yard-cucumber` line is here:

https://github.com/burtlo/yard-cucumber/blob/177e5ad17aa4973660ce646b398118a6408d8913/lib/templates/default/fulldoc/html/setup.rb#L166

which I think is trying to reference the `TreeContext` that is defined in `yard` here:

https://github.com/lsegal/yard/blob/c26eedab6eb3832e91c8fd745ef3e05da4c9a45e/templates/default/fulldoc/html/setup.rb#L177

Everything works fine for me when running `yard doc`, it's just `yard server` that fails, which seems like it's likely to going to be a funky problem to track down. I don't know much of anything about the YARD template architecture; trying to get a debugger going in the `server` process to see poke around.
