### ISSUE TITLE
[warn]: Error loading plugin 'yard-cucumber'

### ISSUE THREAD

**Issue by dianabal4** [burtlo/yard-cucumber#62]
I have installed the yard-cucumber and trying to run rake parrell test but keep getting [warn]: Error loading plugin 'yard-cucumber' 

[warn]: Error loading plugin 'yard-cucumber'
rake aborted!
Don't know how to build task 'parallel:'
/Users/diana/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/diana/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in`<main>'

**Comment by burtlo** [comment]
I don't know the other context around this issue or the setup. It's been a long time. I'm sorry I didn't get to this sooner when it was probably more relevant. Are you still able to reproduce this issue?

Do you have more information your yard configuration?
Your ruby version?
Your gems installed?
