### ISSUE TITLE
I pushed a Cucumber 2.0 compatible version to RubyGems

### ISSUE THREAD

**Issue by tk8817** [burtlo/yard-cucumber#63]
I am sure many of you have found it frustrating to build this into your projects from git-hub, so I thought it would be worthwhile publishing pghalliday's changes as a temporary band-aid. Hopefully we can get in touch with the original author and have the master branch updated/released. 

https://rubygems.org/gems/yard-cucumber2

**Comment by burtlo** [comment]
Sorry. I have become an absentee gem owner

**Comment by burtlo** [comment]
Sorry. I have become an absentee gem owner. @tk8817 perhaps I could add you as a gem owner here to help with releases?

**Comment by tk8817** [comment]
Hi @burtlo , happy to help where I can. Also - apologies if I sounded rude about the lack of an update, myself (and I am sure countless others) are nothing but deeply thankful for this wonderful gem!

**Comment by burtlo** [comment]
Not rude at all. As someone that has does something similar in the past I totally understand your motivation. I appreciate it.

**Comment by jnyman** [comment]
Just a note on this, if I install this particular gem and run the `yard config load_plugins true` command, I get the following:

    [warn]: Error loading plugin 'yard-cucumber2'

It says "warn" but it appears to be an error, given the message. I don't know how to get any more details out of the warning to help diagnose.

**Comment by vikramvi** [comment]
@jeffnyman I'm struck with issue https://github.com/burtlo/yard-cucumber/issues/80 and I think it's because of gem version mismatch.

Can you please share your Gemfile and Gemfile.lock and do you still use this gem or yard-cucumber2 ?

Thanks in advance.

Kind Regards,
Vikram
