### ISSUE TITLE
When generating docs I am missing the Feature context

### ISSUE THREAD

**Issue by cwidhelm** [burtlo/yard-cucumber#73]
Given the feature document:

```
Feature: User delete Company
  As a User
  I want to delete a Company
  So that the Company can no longer use the system

  Scenario: Delete Company
  Scenario: Delete non-existent Company
```

And a default `.yard/config` file.

And the rake command of:

```
YARD::Rake::YardocTask.new do |t|
  t.files   = ['features/**/*.feature', 'features/**/*.rb']
  t.stats_options = ['--list-undoc']
end
```

When I run `rake yard` I get the title and the scenarios, but I am missing the following:
`As a User
  I want to delete a Company
  So that the Company can no longer use the system
`

**Comment by burtlo** [comment]
I believe this is fixed. I cut a new release of the gem 4.0.0 with some changes merged in from the community. If you are still using the gem give it a try.
