### ISSUE TITLE
Query: how to host files within company network

### ISSUE THREAD

**Issue by vikramvi** [burtlo/yard-cucumber#78]
@burtlo Thanks for this amazing plugin, I've started to learn and play around with it for achieving " living documentation".

Can you please clarify what is best way to host within company network ?

Note:

README needs update

User needs to install latest versions of Gherkin, Cucumber and YARD gems, then install yard-cucumber gem. 

Thanks & Regards,
Vikram

**Comment by kapoorlakshya** [comment]
Put it on a VM running Windows and IIS or a Linux box with Apache2? You can generate the docs nightly or based on a trigger when something is merged to master.
