### ISSUE TITLE
README needs to have Gemfile and Gemfile.lock

### ISSUE THREAD

**Issue by vikramvi** [burtlo/yard-cucumber#81]
It will be great help for community if you can share Gemfile and Gemfile.lock, so user won't have any issues running this project.

Currently I'm blocked because of https://github.com/burtlo/yard-cucumber/issues/80

**Comment by burtlo** [comment]
I see a `Gemfile` and `Gemfile.lock` in the project. I know that the `yard-cucumber.gemspec` really defines what was currently defined as a dependency of the project. If I'm incorrect and you need something more, please re-open the issue. I'll take a look at #80 right now.
