### ISSUE TITLE
Tags on scenario outline examples are not recognized

### ISSUE THREAD

**Issue by elhuang** [burtlo/yard-cucumber#85]
This was noted in https://github.com/burtlo/yard-cucumber/issues/25:

"Great, thanks! Each example group can have it's own tags as well, so it would be great if yard-cucumber could be aware of those too." by jmerrifield. 

If this was once working, it does not appear to work anymore with the latest release v 3.1.0.

```
  Scenario Outline: Multiple Example Table
    Given that <Customer> is a valid customer
    And that the product, named '<Product>', is a valid product
    When the customer has purchased the product
    Then I expect the customer to be a member of the '<Product>' group

    @tagA
    Examples: Example group A
     | Customer   | Product   |
     | Customer A | Product A |

    @tagB
    Examples: Example group B
     | Customer   | Product   |
     | Customer B | Product A |
```

see: https://github.com/cucumber/cucumber/blob/e88ca59d72fac9a4a4899b0b5f67732c908b39ea/gherkin/testdata/good/readme_example.feature#L15-L16

**Comment by burtlo** [comment]
Thank the work that you have added fixes this!
