### ISSUE TITLE
No released version of the yard-cucumber gem supports cucumber greater than 3.0.0

### ISSUE THREAD

**Issue by bojingo** [burtlo/yard-cucumber#88]
On September 27th version 3.0.0 of the cucumber gem released. In order to update my acceptance test project to use it, I had to downgrade yard-cucumber to 2.2.3 which doesn't have an upper-bound limit on the version of the cucumber gem.

**Comment by burtlo** [comment]
I need to definitely update this gem. Thank you for the issue.

**Comment by burtlo** [comment]
Release 4.0.0 that has updated the cucumber and gherkin gems. Thanks for the comment and patience.
