### ISSUE TITLE
Nor generating document for java files 

### ISSUE THREAD

**Issue by saxenadeepakkumar** [burtlo/yard-cucumber#90]
I want to use this to generate documentation from java and feature files with jruby. But it is not parsing java files and giving error. It is only generating documentation for only feature files. Is anything required to add to generate document for java files?

**Comment by burtlo** [comment]
There is currently no support in this project to do documentation for Java. I imagine it could be done but I don't know if this project is tooled to do it as I am using YARDoc. Which is focused on Ruby.
