### ISSUE TITLE
Facing uninitialized constant Tree Context

### ISSUE THREAD

**Issue by rpossan** [burtlo/yard-cucumber#94]
Hi,
I'm facing an issue when run yard server and yard-cucumber is loaded maybe on context menu. See the screenshot in attachment.
Ruby 2.5 64, Windows 7. Yard Cucumber 4.0.0

Please, help me with this issue.

![image](https://user-images.githubusercontent.com/157130/46538115-80190c00-c889-11e8-8403-00e24432a12c.png)

**Comment by nrser** [comment]
Seeing exact same issue, just added `yard-cucumber@~>4.0.0` as a dev dep to a project that already had `yard@'~>0.9.15'.

Upon `yard server --relaod` the top-left frame errors out:

<img width="914" alt="screen shot 2018-11-24 at 3 51 48 am" src="https://user-images.githubusercontent.com/207603/48958873-d3abfa00-ef9c-11e8-9736-d24c4c684318.png">

I guess this sitting without response for over a month is not a great indicator that help is on the way, but I still felt like I should try and chime in.

@rpossan you ever figure it out?

BTW I'm Ruby `2.3.7`, OSX `10.13.6` "High Sierra".

**Comment by rpossan** [comment]
> Seeing exact same issue, just added `yard-cucumber@~>4.0.0` as a dev dep to a project that already had `yard@'~>0.9.15'.
> 
> Upon `yard server --relaod` the top-left frame errors out:
> 
> <img alt="screen shot 2018-11-24 at 3 51 48 am" width="914" src="https://user-images.githubusercontent.com/207603/48958873-d3abfa00-ef9c-11e8-9736-d24c4c684318.png">
> 
> I guess this sitting without response for over a month is not a great indicator that help is on the way, but I still felt like I should try and chime in.
> 
> @rpossan you ever figure it out?
> 
> BTW I'm Ruby `2.3.7`, OSX `10.13.6` "High Sierra".

No ... Not yet :( Same issue

**Comment by nrser** [comment]
OK, I'm not sure what's going wrong, but this change seems to fix it:

```Ruby
def class_list(root = Registry.root, tree = self.class.const_get(:TreeContext).new)
```

Change is to this line:

https://github.com/burtlo/yard-cucumber/blob/177e5ad17aa4973660ce646b398118a6408d8913/lib/templates/default/fulldoc/html/setup.rb#L166

`TreeContext` is present as a constant, but something to do with how things are being mixed together in the server process prevents referencing it directly?

**Comment by nrser** [comment]
@rpossan I have the change up in a fork and branch, if you're using a `Gemfile` you can try it with:

```Ruby
gem 'yard-cucumber',
  git: 'https://github.com/nrser/yard-cucumber.git',
  branch: 'nrser-fix-94'
```

**Comment by rpossan** [comment]
Thank you @nrser ! I will set your fix in my Gemfile. Thanks a lot!

**Comment by peagha** [comment]
The PR fixing this issue isn't merged yet, IMO we should keep the issue opened, wdyt?
